// Overlay config shape — identical whether hand-tuned via sliders or
// AI-generated by /api/generate-overlay. This is the tokenizable unit
// (a Pack): parameters only, never video/geometry. Spec §4/§5.

export type GlowPosition = "top-left" | "top-right" | "bottom" | "ambient";
export type ParticleType = "dust" | "rain" | "snow" | "none";

export interface ColorGrade {
  tint: string; // #hex
  saturation: number; // 0.5-2
  warmth: number; // -1 to 1
}

export interface GlowLayer {
  id: string;
  color: string; // #hex
  intensity: number; // 0-3
  position: GlowPosition;
  pulse_speed: number; // 0-2, 0 = static
}

export interface Particles {
  type: ParticleType;
  density: number; // 0-1
}

export interface OverlayConfig {
  color_grade: ColorGrade;
  glow_layers: GlowLayer[];
  particles: Particles;
  vignette: number; // 0-0.5
}

export const MAX_GLOW_LAYERS = 3;
export const GLOW_POSITIONS: GlowPosition[] = ["top-left", "top-right", "bottom", "ambient"];
export const PARTICLE_TYPES: ParticleType[] = ["dust", "rain", "snow", "none"];

export function defaultOverlayConfig(): OverlayConfig {
  return {
    color_grade: { tint: "#7dd3fc", saturation: 1.1, warmth: 0.1 },
    glow_layers: [
      {
        id: crypto.randomUUID(),
        color: "#a78bfa",
        intensity: 1.2,
        position: "ambient",
        pulse_speed: 0.4,
      },
    ],
    particles: { type: "none", density: 0.3 },
    vignette: 0.15,
  };
}
